name: 'JDK via Jabba'
description: 'Set up your GitHub Actions workflow with a specific version of Java via Jabba.'
inputs:
  jdk:
    description: 'The JDK to install. See https://github.com/shyiko/jabba for available expressions.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: orange
  icon: download
