name: Build Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  use-with-default-settings:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: "./"
      with:
        jdk: zulu@1.8.252

    - name: Print Java version
      run: |
        java -version
