name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: battila7/setup-jabba@master
      with:
        java: zulu@1.8.252

    - name: Run a multi-line script
      run: |
        java --version
